= Ladybug Classifier =

== Description ==

This program implements a simple neural network, which is capable of binary classification. In particular, it will determine whether it is a ladybug or caterpillar.

== Structure ==

The program is divided into 3 main parts:

1. Neural Network implementation
2. Demonstration module
3. Data set generator (used for demonstration purposes)

=== 1. Neural Network implementation ===

Neural network is a set of neurons, which are connected to each other. Each neuron has a set of weights, which are used to calculate the output of the neuron. The output of the neuron is calculated as a weighted sum of the inputs, passed through an activation function. The activation function is used to introduce non-linearity into the network.

In our case, neural network has 3 layers: input layer, hidden layer and output layer. The input layer has 2 neurons, the hidden layer has 2 neurons and the output layer has 1 neuron. The input layer is used to pass the input data to the network and the output layer is used to make the final decision.

=== 2. Demonstration module ===

The demonstration module is used to demonstrate the capabilities of the neural network. It generates a data set, which consists of 50 samples. Each sample is a 2D point, which represents a ladybug's or a caterpillar's width and height and a class label numerical representation (0 means ladybug, 1 means caterpillar). The data set is then used to train the neural network. There are also 5 samples for testing the network and evaluating its performance.

=== 3. Data set generator ===

The generator produces both training and samples, which are generated by particular rules. The ladybug is square and its dimensions lie between 2.0 and 5.0 units, while caterpillar's length is from 7.0 to 15.0 and width is from 0.5 to 1.5 units.